#!/usr/bin/env bash
# Write docker-compose.override.yaml: one read-only mount per indexed directory.
#
# Reached through `make mounts`, and by `make install` before it hands a tree
# to the API. A project reading one directory is mounted whole at
# /code/<project>; a project reading several has each of them at
# /code/<project>/<alias>, which is also the first segment of every node id
# that directory produces. Either way a pass over several projects reads the
# files of all of them rather than the one that happened to be mounted.
#
# The list comes from `ctxgraph.mounts`, which names each project by the same
# rule the indexer applies. The existence check has to be here instead: a bind
# mount whose source is missing is created by Docker as an empty directory
# rather than refused, and indexing an empty tree prunes a whole graph.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

# `docker compose` is two words, and a plain "$COMPOSE" would be looked up as
# one binary of that name.
read -r -a compose <<< "${COMPOSE:-docker compose}"

output="docker-compose.override.yaml"

# The credentials and the default tree live in .env, which make does not
# source. That tree is the one a bare install onboards, so it needs a mount
# whether or not it has ever been indexed before. Not under CREATE: that run
# is registering a project that reads no directory, and the default tree would
# quietly become the one it reads.
env_value() {
    sed -n "s/^$1=//p" .env 2> /dev/null | tail -1
}

if [ -z "${CREATE:-}" ]; then
    : "${ADD:=$(env_value PROJECT_PATH)}"
fi

# REGISTER=1 stores the added tree as a project before the listing is taken,
# which is what `make install` passes and nothing else does: a bare run and
# `make summarize` both arrive with a path of their own, and neither of them
# is onboarding anything.
#
# ALIAS names the directory inside the project, DROP and PROMOTE change a
# selection that already exists, and CREATE registers a project that reads
# nothing yet. All four are onboarding and the source targets; a bare run
# passes none of them and only lists.
args=()
if [ -n "${ADD:-}" ]; then
    args+=(--add "$ADD")
    if [ -n "${ALIAS:-}" ]; then
        args+=(--alias "$ALIAS")
    fi
    if [ "${REGISTER:-0}" != "0" ]; then
        args+=(--register)
        if [ -n "${CREATE:-}" ]; then
            args+=(--create)
        fi
        if [ -n "${PROJECT_TYPE:-}" ]; then
            args+=(--type "$PROJECT_TYPE")
        fi
    fi
fi
if [ -n "${PROJECT_NAME:-}" ]; then
    args+=(--name "$PROJECT_NAME")
fi
if [ -n "${DROP:-}" ]; then
    args+=(--drop "$DROP")
fi
if [ -n "${PROMOTE:-}" ]; then
    args+=(--promote "$PROMOTE")
fi

# stderr is kept rather than discarded: a registration refused because the
# name and the path disagree is the one failure here worth reading.
errors="$(mktemp)"
trap 'rm -f "$errors"' EXIT
if ! listing="$("${compose[@]}" --profile index run --rm -T graphify \
        python -m ctxgraph.mounts ${args[@]+"${args[@]}"} 2> "$errors")"; then
    sed 's/^/  /' "$errors" >&2
    echo "Cannot list the indexed trees. Is the stack up? Try 'make up'." >&2
    exit 1
fi
# What it wrote there on the way through: the registration it made, or a type
# it did not recognise. Both are worth seeing on a run that succeeded.
if [ -s "$errors" ]; then
    sed 's/^/  /' "$errors" >&2
fi

mounts=()
skipped=()
while IFS=$'\t' read -r name alias root; do
    [ -n "$name" ] || continue
    # The listing is generated inside the graphify container, so an image
    # older than this script prints the two columns it used to and the host
    # path lands in $alias, leaving $root empty. Refusing here leaves the
    # current override in place; writing it would mount nothing at all.
    if [ -z "$root" ]; then
        echo "The graphify image is older than this script: its listing has" >&2
        echo "no alias column, so the override was left as it is." >&2
        echo "Whatever this run registered is stored and nothing is lost." >&2
        echo "Run 'make build', then 'make mounts'." >&2
        exit 1
    fi
    # A tab is IFS whitespace, so two of them collapse into one delimiter and
    # the unnamed source cannot travel as an empty column. It travels as "-",
    # which no alias can be.
    [ "$alias" != "-" ] || alias=""
    target="/code/$name"
    label="$name"
    if [ -n "$alias" ]; then
        target="$target/$alias"
        label="$name/$alias"
    fi
    if [ ! -d "$root" ]; then
        skipped+=("$label ($root)")
        continue
    fi
    mounts+=("  - $root:$target:ro")
done <<< "$listing"

# Written aside and moved into place, so a failure here cannot leave compose
# reading half a file.
work="$(mktemp "$output.XXXXXX")"
trap 'rm -f "$work" "$errors"' EXIT

{
    echo "# Generated by 'make mounts'. Do not edit:"
    echo "# 'make install' rewrites it from the projects table. Ignored by git,"
    echo "# because every line of it is a path on this machine."
    if [ "${#mounts[@]}" -eq 0 ]; then
        echo "x-code-mounts: &code-mounts []"
    else
        echo "x-code-mounts: &code-mounts"
        printf '%s\n' "${mounts[@]}"
    fi
    echo
    echo "services:"
    # Both services that touch files: the indexer walks the trees, the API
    # serves their text to the dashboard and to a remote worker.
    for service in graphify worker-api; do
        echo "  $service:"
        echo "    volumes: *code-mounts"
    done
} > "$work"

mv "$work" "$output"
rm -f "$errors"
trap - EXIT

echo "$output: ${#mounts[@]} director(ies) mounted under /code"
if [ "${#skipped[@]}" -gt 0 ]; then
    for entry in "${skipped[@]}"; do
        echo "  skipped, no such directory on this host: $entry" >&2
    done
fi
