#!/usr/bin/env bash
# Write docker-compose.override.yaml: one read-only mount per indexed tree.
#
# Reached through `make mounts`, and by `make index` and `make install` before
# they touch a tree. Every codebase is mounted at /code/<project>, so a pass
# over several projects reads the files of all of them rather than the one that
# happened to be mounted.
#
# The list comes from `ctxgraph.mounts`, which names each project by the same
# rule the indexer applies. The existence check has to be here instead: a bind
# mount whose source is missing is created by Docker as an empty directory
# rather than refused, and indexing an empty tree prunes a whole graph.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

# `docker compose` is two words, and a plain "$COMPOSE" would be looked up as
# one binary of that name.
read -r -a compose <<< "${COMPOSE:-docker compose}"

output="docker-compose.override.yaml"

# The credentials and the default tree live in .env, which make does not
# source. A bare `make index` indexes that tree, so it needs a mount whether
# or not it has ever been indexed before.
env_value() {
    sed -n "s/^$1=//p" .env 2> /dev/null | tail -1
}

: "${ADD:=$(env_value PROJECT_PATH)}"

args=()
if [ -n "${ADD:-}" ]; then
    args+=(--add "$ADD")
    if [ -n "${PROJECT_NAME:-}" ]; then
        args+=(--name "$PROJECT_NAME")
    fi
fi

if ! listing="$("${compose[@]}" --profile index run --rm -T graphify \
        python -m ctxgraph.mounts ${args[@]+"${args[@]}"} 2> /dev/null)"; then
    echo "Cannot list the indexed trees. Is the stack up? Try 'make up'." >&2
    exit 1
fi

mounts=()
skipped=()
while IFS=$'\t' read -r name root; do
    [ -n "$name" ] || continue
    if [ ! -d "$root" ]; then
        skipped+=("$name ($root)")
        continue
    fi
    mounts+=("  - $root:/code/$name:ro")
done <<< "$listing"

# Written aside and moved into place, so a failure here cannot leave compose
# reading half a file.
work="$(mktemp "$output.XXXXXX")"
trap 'rm -f "$work"' EXIT

{
    echo "# Generated by 'make mounts'. Do not edit: 'make index' and"
    echo "# 'make install' rewrite it from the projects table. Ignored by git,"
    echo "# because every line of it is a path on this machine."
    if [ "${#mounts[@]}" -eq 0 ]; then
        echo "x-code-mounts: &code-mounts []"
    else
        echo "x-code-mounts: &code-mounts"
        printf '%s\n' "${mounts[@]}"
    fi
    echo
    echo "services:"
    echo "  graphify:"
    echo "    volumes: *code-mounts"
} > "$work"

mv "$work" "$output"
trap - EXIT

echo "$output: ${#mounts[@]} tree(s) mounted under /code"
if [ "${#skipped[@]}" -gt 0 ]; then
    for entry in "${skipped[@]}"; do
        echo "  skipped, no such directory on this host: $entry" >&2
    done
fi
